### PR TITLE
page ClassAttendance created

### PR DESCRIPTION
**Pull request by Denis-Andrei**
This PR includes:
 - ClassAttendance Table Component created
 - ClassAttendance Page created
 - route in the routes folder included 

ADDED LATER:
- Page PD Skills created
- PDSkills Table Component Created
- Page Soon created( to replace StudentInfo and Laptop page)
- route updated

### CODE REVIEW

**Review by ISTANBULBEKLE — APPROVED** [review]
Great Job, guys.

**Review by Osman-Hajr — COMMENTED** [review]
Looks good for me

**Review by Osman-Hajr — APPROVED** [review]
Looks good

**Review by Osman-Hajr — APPROVED** [review]

**Review by sadatakhtar — APPROVED** [review]
Great Job

**Pull request merged**
