### PR TITLE
/student-tracker/Edu-Homework page DONE

### PR DESCRIPTION
**Pull request by Denis-Andrei**
This PR includes:

- some more variables created in main.scss
- EduHomeworkTable Component created
- fakeData file(can be an example for the backend team)
- EduHomework Page created
- added route for the page mentioned above

### CODE REVIEW

**Review by ISTANBULBEKLE — APPROVED** [review]
Denis, good job. I hope we will see as a showcase soon also.

**Review by Ade0211 — CHANGES_REQUESTED** [review]
Great work Denis. However, for the front page, there is only a forward slash without the front for the path("/"), so that it wont conflict what I will be pushing to the github..

**Comment by Denis-Andrei** [comment]
> Great work Denis. However, for the front page, there is only a forward slash without the front for the path("/"), so that it wont conflict what I will be pushing to the github..

For the front page the route is just '/'. Shouldn't be any conflict. When a user will access the app, the front page is the one that we want them to see

**Review by Ade0211 — APPROVED** [review]
Good Job Denis.

**Review by sadatakhtar — APPROVED** [review]
Nice work Denis, I will update the backend with the requested data

**Pull request merged**
